name: Sync to Hugging Face hub
on:
  push:
    branches: [main, feature/paper-2-code-pivot-10436912331149560913]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://AUXteam:${HF_TOKEN}@huggingface.co/spaces/AUXteam/Paper2Code HEAD:main
